notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

services:
  - docker

script:
 - set -e
 - echo 'Build and check docker image'
 - docker build -t telomerecat .
 - docker images | grep -c telomerecat
 - docker run -t --rm telomerecat telomerecat bam2length -h
 - docker run -t --rm telomerecat telomerecat bam2telbam -h
 - docker run -t --rm telomerecat telomerecat telbam2length -h
